import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { loadArticles } from "../scripts/lib/notebook.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));

test("Ingest stages an archived draft; publication requires translations and inline annotations", async (t) => {
  const temporary = await fs.mkdtemp(path.join(os.tmpdir(), "english-notebook-test-"));
  t.after(() => fs.rm(temporary, { recursive: true, force: true }));
  for (const directory of ["scripts", "public", "content"]) await fs.cp(path.join(root, directory), path.join(temporary, directory), { recursive: true });
  await fs.mkdir(path.join(temporary, "inbox"));
  const articles = await loadArticles(root);
  const fixtureId = String(Math.max(...articles.map((article) => Number(article.id))) + 1);
  const baselineCount = articles.filter((article) => !article.draft).length;
  const raw = `# 英语一精读 ${fixtureId}｜Workflow Fixture\n\n## 原文\n\nChronic stress matters.\n\n## 重点词汇\n\nchronic = 长期的；慢性的\n`;
  await fs.writeFile(path.join(temporary, "inbox", "new-reading.md"), raw);
  const run = (...args) => spawnSync(process.execPath, args, { cwd: temporary, encoding: "utf8" });
  const ingest = run("scripts/ingest.mjs", "--topic", "医疗与健康");
  assert.equal(ingest.status, 0, ingest.stderr);
  const result = JSON.parse(ingest.stdout);
  assert.equal(await fs.readFile(path.join(temporary, result.archive), "utf8"), raw);
  const sitePath = path.join(temporary, "dist", "data", "site.json");
  assert.equal(JSON.parse(await fs.readFile(sitePath)).articles.length, baselineCount);
  const baselineVocabulary = JSON.parse(await fs.readFile(path.join(temporary, "data", "vocabulary.json")));
  const beforeChronic = baselineVocabulary.find((entry) => entry.term === "chronic");
  assert.notEqual(run("scripts/reading.mjs", "check", "--id", fixtureId).status, 0);
  const readingPath = path.join(temporary, "content", "readings", result.article.replace(/\.md$/, ".json"));
  const reading = JSON.parse(await fs.readFile(readingPath));
  reading.units[0].translation = "慢性压力很重要。";
  reading.units[0].annotations = [{ text: "Chronic", type: "vocabulary", meaning: "长期的；慢性的", context: "Chronic stress = 慢性压力", note: "测试资料，不加入正式内容。" }];
  await fs.writeFile(readingPath, JSON.stringify(reading));
  const publication = run("scripts/reading.mjs", "publish", "--id", fixtureId);
  assert.equal(publication.status, 0, publication.stderr);
  assert.equal(JSON.parse(await fs.readFile(sitePath)).articles.length, baselineCount + 1);
  const vocabulary = JSON.parse(await fs.readFile(path.join(temporary, "data", "vocabulary.json")));
  const chronic = vocabulary.find((entry) => entry.term === "chronic");
  assert.equal(chronic.appearances, beforeChronic.appearances + 1);
  assert.equal(chronic.sources.length, beforeChronic.sources.length + 1);
  assert.equal(chronic.errorCount, beforeChronic.errorCount);
  await fs.rm(readingPath);
  const blocked = run("scripts/build.mjs");
  assert.notEqual(blocked.status, 0);
  assert.match(blocked.stderr, /缺少逐句翻译和正文批注/);
});
